spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library-mangement?serverTimezone=GMT%2b8 # ????
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启数据库字段下划线 转为驼峰
    #以日志的方式进行输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #指定entity扫描包类让mybatis自定扫描到自定义的entity。
  type-aliases-package: com.example.springboot.entity
